program SHAWDHM27
!***********************************************************************
!
      PROGRAM SHAW
!
!     This version has modifications for turbulent flux within the
!     canopy described in Flerchinger et al. (2012)
!
!     This version uses the x-parameter in computing diffuse
!     radiation transmission through the canopy
!
!     This version includes radiation scattering algorithms
!     from Flerchinger and Yu (2007)
!
!     This version includes updated downward longwave radiation
!     algoritms based on analysis of Flerchinger et al (2008)
!
!*********************************************************
!***  This version assumes PPT in MM and wind in m/s *****
!*********************************************************
!
!     THIS IS THE DRIVER FOR THE SHAW MODEL (VERSION 2.7 Beta)
!
!     (PROVISIONS FOR SATURATED CONDITIONS)
!
!     DEVELOPED BY: GERALD N. FLERCHINGER
!                   USDA - ARS
!                   800 PARK BLVD., SUITE 105
!                   BOISE, IDAHO 83712
!                   TELEPHONE: 208-422-0716
!                   E-MAIL: gerald.flerchinger@ars.usda.gov
!
!***********************************************************************
!
      COMMON /CONSTN/ LF,LV,LS,G,UGAS,RHOL,RHOI,RHOM,RHOOM,RHOA,CL,CI,
     >                CM,COM,CA,CV,CR,VONKRM,VDIFF,PRESUR,P0,
     >                TKL,TKI,TKA,TKR,TKSA,TKSI,TKCL,TKOM
      REAL LF,LV,LS
!
      REAL SUNHOR(24),TMPDAY(24),WINDAY(24),HUMDAY(24),PRECIP(24),
     >     SNODEN(24),SOITMP(24),VLCDAY(24),SOILXT(50,24)
!
      REAL PLTHGT(8),PLTWGT(8),PLTLAI(8),ROOTDP(8),DCHAR(8),
     >     TCCRIT(8),RSTOM0(8),RSTEXP(8),PLEAF0(8),
     >     RLEAF0(8),RROOT0(8),PCANDT(8),CANALB(8),XANGLE(8),CLUMPNG(8)
      REAL ZC(11),TCDT(11),TLCDT(8,10),VAPCDT(11),WCANDT(10)
      REAL ZSP(100),DZSP(100),RHOSP(100),TSPDT(100),DLWDT(100),WLAG(11)
      REAL ZR(10),RHOR(10),TRDT(10),VAPRDT(10),GMCDT(10)
!
      REAL ZS(50),TSDT(50),MATDT(50),CONCDT(10,50),
     >     VLCDT(50),VICDT(50),SALTDT(10,50)
      REAL DGRADE(10),SLTDIF(10),ASALT(50),DISPER(50)
!
      INTEGER YRSTAR,HRSTAR,YREND,HOUR,YEAR
      INTEGER LEVEL(6),LVLOUT(15)
      INTEGER ITYPE(8),ICESDT(50),ICESPT(100)
!
!     SET FLAG INDICATING FIRST TIME THROUGH SUBROUTINES FOR
!     INITIALIZATION
      INITAL=0
!
!
!**** INPUT GENERAL INFORMATION, PROPERTIES, AND INITIAL CONDITIONS
!
      CALL INPUT (NC,NSP,NR,NS,TOLER,LEVEL,MTSTEP,MZCINP,MPLTGRO,
     >  INPH2O,MWATRXT,LVLOUT,IVLCBC,ITMPBC,NPLANT,PLTHGT,PLTWGT,PLTLAI,
     >  ROOTDP,DCHAR,TCCRIT,RSTOM0,RSTEXP,PLEAF0,RLEAF0,RROOT0,
     >  CANALB,CANMA,CANMB,WCMAX,XANGLE,CLUMPNG,ITYPE,ZC,WCANDT,
     >  ZSP,DZSP,RHOSP,TSPDT,DLWDT,ICESPT,SNOTMP,
     >  GMCDT,GMCMAX,RLOAD,ZRTHIK,COVER,ALBRES,RESCOF,
     >  ZS,TSDT,VLCDT,VICDT,MATDT,CONCDT,ICESDT,SALTDT,ALBDRY,ALBEXP,
     >  DGRADE,SLTDIF,ASALT,DISPER,
     >  ZMSRF,ZHSRF,ZERSRF,ZMSP,ZHSP,HEIGHT,PONDMX,
     >  JSTART,YRSTAR,HRSTAR,JEND,YREND,NHRPDT,WDT,
     >  ALATUD,SLOPE,ASPECT,HRNOON)
!
      JULIAN=JSTART
      HOUR=HRSTAR
      YEAR=YRSTAR
      MAXJUL=365
      IF (MOD(YEAR,4) .EQ. 0)  MAXJUL=366
!
!**** DEFINE INITIAL BOUNDARY CONDITIONS FOR THE DAY
      IF (INPH2O.NE.1) THEN
!        INPUT SOIL MOISTURE IS WATER CONTENT
         VLCDAY(HOUR)=VLCDT(NS) + VICDT(NS)*RHOI/RHOL
        ELSE
!        INPUT SOIL MOISTURE IS MATRIC POTENTIAL
         VLCDAY(HOUR)=MATDT(NS)
      END IF
      SOITMP(HOUR)=TSDT(NS)
!
      CALL DAYINP (JULIAN,YEAR,MAXJUL,HOUR,NHRPDT,MTSTEP,INITAL,
     >    MPLTGRO,MWATRXT,NS,ALATUD,HRNOON,SUNHOR,TMPDAY,WINDAY,HUMDAY,
     >    PRECIP,SNODEN,SOITMP,VLCDAY,SOILXT,NPLANT,PLTHGT,DCHAR,PLTWGT,
     >    PLTLAI,ROOTDP)
      CALL CLOUDY (CLOUDS,ALATUD,DECLIN,HAFDAY,SUNHOR,JULIAN,NHRPDT)
!
!**** BEGIN SIMULATION
      IF (LVLOUT(13) .NE. 0) WRITE (6,525)
!
!
!**** START OF A NEW HOUR - UPDATE VALUES ASSUMED CONSTANT OVER THE HOUR
  100 DT=NHRPDT*3600.
      HOUR=HOUR+NHRPDT
      IF (HOUR .GT. 24) THEN
!        START A NEW DAY
         HOUR=HOUR-24
         JULIAN=JULIAN + 1
         IF (JULIAN .GT. MAXJUL) THEN
            JULIAN=JULIAN-MAXJUL
            YEAR=YEAR + 1
            MAXJUL=365
            IF (MOD(YEAR,4) .EQ. 0)  MAXJUL=366
         END IF
         IF (YEAR .EQ. YREND  .AND.  JULIAN .GT. JEND)   STOP
         IF (YEAR .GT. YREND) STOP
         CALL DAYINP (JULIAN,YEAR,MAXJUL,0,NHRPDT,MTSTEP,1,
     >    MPLTGRO,MWATRXT,NS,ALATUD,HRNOON,SUNHOR,TMPDAY,WINDAY,HUMDAY,
     >    PRECIP,SNODEN,SOITMP,VLCDAY,SOILXT,NPLANT,PLTHGT,DCHAR,PLTWGT,
     >    PLTLAI,ROOTDP)
         CALL CLOUDY (CLOUDS,ALATUD,DECLIN,HAFDAY,SUNHOR,JULIAN,NHRPDT)
      END IF
!
      IF (JULIAN .EQ. LEVEL(2)  .AND.  HOUR .EQ. LEVEL(3)) THEN
!        CHANGE LEVEL OF OUTPUT
         LVL = LEVEL(1)
         LEVEL(1) = LEVEL(4)
         LEVEL(2) = LEVEL(5)
         LEVEL(3) = LEVEL(6)
         LEVEL(4) = LVL
         LEVEL(5) = JULIAN
         LEVEL(6) = HOUR
      END IF
!
C
      CALL GOSHAW (JULIAN,HOUR,YEAR,NHRPDT,WDT,DT,INITAL,
     >  NC,NSP,NR,NS,TOLER,LEVEL,MZCINP,
     >  INPH2O,MWATRXT,LVLOUT,IVLCBC,ITMPBC,
     >  NPLANT,PLTHGT,PLTWGT,PLTLAI,ROOTDP,DCHAR,TCCRIT,RSTOM0,RSTEXP,
     >  PLEAF0,RLEAF0,RROOT0,PCANDT,CANALB,CANMA,CANMB,WCMAX,XANGLE,
     >  CLUMPNG,ITYPE,ZC,TCDT,TLCDT,VAPCDT,WCANDT,
     >  ZSP,DZSP,RHOSP,TSPDT,DLWDT,ICESPT,WLAG,STORE,SNOWEX,SNOTMP,
     >  ZR,RHOR,TRDT,VAPRDT,GMCDT,GMCMAX,RLOAD,ZRTHIK,COVER,ALBRES,
     >  RESCOF,DIRRES,
     >  ZS,TSDT,VLCDT,VICDT,MATDT,CONCDT,ICESDT,SALTDT,ALBDRY,ALBEXP,
     >  DGRADE,SLTDIF,ASALT,DISPER,
     >  ZMSRF,ZHSRF,ZERSRF,ZMSP,ZHSP,HEIGHT,POND,PONDMX,
     >  ALATUD,SLOPE,ASPECT,HRNOON,CLOUDS,DECLIN,HAFDAY,
     >  SUNHOR(HOUR),TMPDAY(HOUR),WINDAY(HOUR),HUMDAY(HOUR),
     >  PRECIP(HOUR),SNODEN(HOUR),SOITMP(HOUR),VLCDAY(HOUR),
     >  SOILXT(1,HOUR))
!
      INITAL=1
!
      GO TO 100
!
  525 FORMAT(/20X,'Day   Hour   Year   Min Steps  Max Steps'/)
      END
end program SHAWDHM27
